packages:
  - packages/*
  - playground

catalog:
  '@astrojs/starlight': 0.37.1
  '@biomejs/biome': 2.3.10
  astro: 5.16.6
  sharp: 0.34.5
  tsdown: 0.18.3
  typescript: 5.9.3

onlyBuiltDependencies:
  - esbuild
  - sharp
