packages:
  - packages/*
  - docs

catalog:
  "@astrojs/markdoc": 0.15.10
  "@astrojs/starlight": 0.37.1
  "@astrojs/starlight-markdoc": 0.5.1
  "@biomejs/biome": 2.3.11
  "@types/picomatch": 4.0.2
  astro: 5.16.6
  astro-og: 0.3.2
  pkg-pr-new: 0.0.62
  picomatch: 4.0.3
  sharp: 0.34.5
  tsdown: 0.18.3
  typescript: 5.9.3

onlyBuiltDependencies:
  - esbuild
  - sharp
