packages:
  - packages/*
  - playground

catalog:
  '@astrojs/starlight': 0.35.1
  '@biomejs/biome': 2.1.2
  astro: 5.12.2
  sharp: 0.34.3
  tsdown: 0.13.0
  typescript: 5.8.3

onlyBuiltDependencies:
  - esbuild
  - sharp
